In [1]:
import torch

In [7]:
a = torch.tensor([5.])
b = torch.tensor([6.])
a.requires_grad = True
b.requires_grad = True
c = a * b

In [29]:
c = a * b

In [30]:
c.backward()

In [26]:
g = a.grad.data
a.data.add_(g)

tensor([17.])

In [28]:
a.grad

tensor([0.])

In [27]:
a.grad.data.zero_()

tensor([0.])

In [22]:
a.grad

tensor([0.])